spring.application.name=booking_tour
spring.datasource.url=jdbc:mysql://localhost:3306/TourDB
spring.datasource.username=root
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080